### ISSUE TITLE
Add The Billings Gazette

### ISSUE THREAD

**Issue by PrestonStahley** [operasoftware/pwa-list#101]
https://billingsgazette.com/pwa

A local newspaper PWA.

Pull request https://github.com/operasoftware/pwa-list/pull/95

**Comment by paulirish** [comment]
Nice work on this! very nice.

**Comment by PrestonStahley** [comment]
Thanks, @paulirish!

Thanks for all of the great work you do on Chrome DevTools, lighthouse, etc!

**Comment by pepelsbey** [comment]
@PrestonStahley, thank you for suggestion! Do you have a vector icon? I also found that two pictures declared in your manifest are not available:

![image](https://cloud.githubusercontent.com/assets/105274/17670744/19faab2e-631c-11e6-83d6-b0193e69d682.png)

**Comment by pepelsbey** [comment]
Found it in [PDF](http://bloximages.chicago2.vip.townnews.com/billingsgazette.com/content/tncms/assets/v3/editorial/f/d0/fd09805a-c0c8-11e3-b717-0019bb2963f4/54905de9b2d35.pdf.pdf) :) Will add it to the list shortly.

**Comment by pepelsbey** [comment]
Right, found a PR.

**Comment by PrestonStahley** [comment]
Awesome! I included a .svg in the pull request https://github.com/operasoftware/pwa-list/pull/95 and I can get you an .ai file as well if you'd like.

The icon paths in the manifest have also been fixed.

Thanks!

**Comment by pepelsbey** [comment]
Merged, will be deployed shortly. Thank you again for the nice PWA example!
