### ISSUE TITLE
Add chromestatus.com

### ISSUE THREAD

**Issue by ebidel** [operasoftware/pwa-list#104]
demo: https://www.chromestatus.com/features
src: https://github.com/GoogleChrome/chromium-dashboard

**Comment by pepelsbey** [comment]
Thank you for suggestion! Will add it shortly. Just a side note: is it OK that [https://chromestatus.com/features](https://chromestatus.com/features) (without `www`) is not available? I’d expect a redirect to `www` instead.

**Comment by ebidel** [comment]
Yea, that's never worked. Silly naked domain + app engine + SSL Google Apps.

**Comment by pepelsbey** [comment]
@ebidel, merged and deployed. I also made a [nice looking vector icon](https://pwa.rocks/images/chrome-status.svg) (only 2.7 KB) based on original one.

**Comment by ebidel** [comment]
oooo, thanks. I might steal that!
