### ISSUE TITLE
Flipboard does not have a Service Worker

### ISSUE THREAD

**Issue by mykeels** [operasoftware/pwa-list#108]
Hi, I noticed that https://flipboard.com does not have a service worker and does not load offline. How come it's in the list?

**Comment by pepelsbey** [comment]
They have it when you’re emulating a proper device or it’s loaded with `/?display=standalone` (not sure about the latter).

![image](https://cloud.githubusercontent.com/assets/105274/18611221/3b3ddff0-7d4c-11e6-8ca2-2d49b1e96af6.png)

Sure, It’s not the best approach, but still valid.
