### ISSUE TITLE
Suggestion: Add BaBe

### ISSUE THREAD

**Issue by owencm** [operasoftware/pwa-list#22]
This is a new nice PWA for news in Indonesia: https://app.babe.co.id

**Comment by andreasbovens** [comment]
Nice one, @owencm - sorry for the late reply here. We've been overwhelmed with other stuff. We'll include this one for sure :+1:

**Comment by andreasbovens** [comment]
Found a large icon here: https://assets.jalantikus.com/assets/cache/300/300/apps/2016/02/06/babe-baca-berita-indonesia-icon.png
