### ISSUE TITLE
Add QR Code Scanner

### ISSUE THREAD

**Issue by gokulkrishh** [operasoftware/pwa-list#25]
https://qrcode-scanner.herokuapp.com

**Comment by gokulkrishh** [comment]
Link to moved to https://qrcodescan.in

**Comment by shwetank** [comment]
Hi,

On load, the button for enabling a scan appear's for a brief moment before dissappearing - effectively leaving a blank page (apart from the header). 

Tested on Opera for Android Beta and stable, as well as Chrome Dev and stable. Can you take a look at fixing that? :)

**Comment by gokulkrishh** [comment]
@shwetank Thanks for reporting. Can you give me device detail in which you have tested and browser versions ??

**Comment by shwetank** [comment]
Sure. 

I tested on a Nexus 6P. 

Opera for Android (latest stable) -  36.0.2126.101812 
Chrome for Android Dev - v 51.0.2693.2
Chrome for Android Stable - v 49.0.2623.105

Screenshot below. 

![qrcodescanin](https://cloud.githubusercontent.com/assets/43538/14280365/01dff870-fb50-11e5-9697-e54c934a184f.png)

**Comment by shwetank** [comment]
Nevermind, I just noticed it was http and not https. When going to https it works fine.

**Comment by shwetank** [comment]
Works quite well. Nicely done! :+1:

**Comment by gokulkrishh** [comment]
@shwetank Thanks. I have checked, its working fine :) :+1:

**Comment by gokulkrishh** [comment]
@shwetank I am adding a rule to redirect to https by default in cloudflare

**Comment by shwetank** [comment]
@gokulkrishh Yes, thats a good idea.

**Comment by gokulkrishh** [comment]
@shwetank I am done :). Now qrcodescan.in goes to https://qrcodescan.in

**Comment by shwetank** [comment]
Awesome :100:

**Comment by gokulkrishh** [comment]
Closing it in favor to https://github.com/operasoftware/pwa-list/pull/30#issuecomment-206351032 PR comment
