### ISSUE TITLE
Add BB8 demo 

### ISSUE THREAD

**Issue by andreasbovens** [operasoftware/pwa-list#27]
https://operasoftware.github.io/bb8/

**Comment by mathiasbynens** [comment]
Hmm, this is only useful for people who own [the BB-8 toy](http://store.sphero.com/collections/bb-8-by-sphero/products/bb-8-by-sphero).

*If* we add it, I think we should wait until Web Bluetooth is enabled by default.

**Comment by andreasbovens** [comment]
Good point, @mathiasbynens. Closing for now.
