### ISSUE TITLE
Add SVGOMG

### ISSUE THREAD

**Issue by igoradamenko** [operasoftware/pwa-list#34]
Hi!

Yesterday PWA needs to have an SVG icon, but now in README says that PWA needs to have just a PNG icon. If it is not a mistake, SVGOMG is a candidate to your list.

Link: https://jakearchibald.github.io/svgomg/

- [x] HTTPS;
- [x] `name` (very short), `start_url` and set of PNG icons from 192×192 to 512×512;
- [x] Service Worker.

**Comment by mathiasbynens** [comment]
Currently, only PNG icons are supported for the home screen icons in Chrome and Opera for Android.

The reason we ask for an SVG is because that’s what we use on our pwa-list website. @jakearchibald do you have an SVG version of https://jakearchibald.github.io/svgomg/imgs/icon.png?

**Comment by mathiasbynens** [comment]
Currently, only PNG icons are supported for the home screen icons in Chrome and Opera for Android.

The reason we ask for an SVG is because that’s what we use on our pwa-list website. @jakearchibald do you have an SVG version of https://jakearchibald.github.io/svgomg/imgs/icon.png?

**Comment by jakearchibald** [comment]
I do! https://github.com/jakearchibald/svgomg/blob/master/src/test-svgs/svgo-logo.svg

**Comment by mathiasbynens** [comment]
Closing in favor of #35.

**Comment by pepelsbey** [comment]
Done: https://operasoftware.github.io/pwa-list/
