### ISSUE TITLE
Add Snapdrop

### ISSUE THREAD

**Issue by ithinkihaveacat** [operasoftware/pwa-list#36]
See <https://snapdrop.net>.

**Comment by mathiasbynens** [comment]
Currently getting a 502 error.

**Comment by ithinkihaveacat** [comment]
@capira12 Can you fix?

**Comment by andreasbovens** [comment]
Seems like it works fine now.

**Comment by mathiasbynens** [comment]
Not for me :/

**Comment by andreasbovens** [comment]
Ah no, it was the SW kicking in. New browser window shows a 502.

**Comment by capira12** [comment]
Sorry guys! forever crashed. 
It is up again
