### ISSUE TITLE
Suggestion: Currency Calculator 

### ISSUE THREAD

**Issue by helloguille** [operasoftware/pwa-list#43]
Hi!

I'd like to suggest the currency calculator I developed, which is available in English and German at the moment.

https://currency-x.com

- HTTPS
- SW, offline first.
- Manifest Icon in multiple sizes
- Mobile friendly
- Ad supported with Google Adsense

PageSpeed Insights (mobile)
- 73 / 100 Speed
- 99 / 100 User Experience

I attach PNG icon, let me know whether I should  provide SVG or PSD file as well.

Thanks!
Guillermo Gonzalez

![512](https://cloud.githubusercontent.com/assets/17315/14455384/8257db9a-009f-11e6-906b-4dc6add1d3de.png)

**Comment by mathiasbynens** [comment]
Yes, please provide an SVG icon as well.

**Comment by helloguille** [comment]
Done! (BTW: 
[Icon.svg.zip](https://github.com/operasoftware/pwa-list/files/214693/Icon.svg.zip)

I used https://cloudconvert.com to generate it from an Adobe Illustrator file)

**Comment by mathiasbynens** [comment]
Thanks! Btw, in Adobe Illustrator you can export / save as SVG.

**Comment by helloguille** [comment]
Thanks!
