### ISSUE TITLE
You could add my Web NFC shopping card app

### ISSUE THREAD

**Issue by kenchris** [operasoftware/pwa-list#5]
https://weneed-1147.appspot.com

It has a "fake mode" so most of the UI works fine without the actual Web NFC support.

**Comment by marco-c** [comment]
There are a few problems while running your app in Firefox.

For example, you're using `navigator.webkitGetUserMedia`.

**Comment by kenchris** [comment]
OK, let me fix that tomorrow. If you run into additional problems, please tell me

**Comment by kenchris** [comment]
OK, fixed :)

**Comment by marco-c** [comment]
Great, thank you!

**Comment by kenchris** [comment]
Added a PR: https://github.com/operasoftware/pwa-list/pull/19
