### ISSUE TITLE
Selio App

### ISSUE THREAD

**Issue by julianmartinezmansell** [operasoftware/pwa-list#55]
Hi Opera team!
Exciting times for progressive web apps! We have built a fully functioning local market app on ReactJS and full PWA technology. 

I've also made a short presentation with some of our learnings, both technical and marketing. I hope you find it interesting:
http://www.slideshare.net/julianmartinez2/building-selio-a-local-market-progressive-web-app

The URL is https://www.selioapp.com  (best viewed from a smartphone currently)

**Comment by pepelsbey** [comment]
Great app, we’ll add it shortly.

BTW, you have a problem with serificate for non-www version of your domain: your sertificate is issued for `*.selioapp.com`, but when there’s no `www` it doesn’t match `https://selioapp.com/` and it’s not secure though it’s on HTTPS:

![image](https://cloud.githubusercontent.com/assets/105274/15260592/4f953b38-1960-11e6-823a-7296d3bd8d52.png)

**Comment by pepelsbey** [comment]
Do you have app logo in SVG or any other vector format?

**Comment by julianmartinezmansell** [comment]
Fixed the problem with the selioapp.com version thanks! :)

**Comment by julianmartinezmansell** [comment]
Hi, just a quick note to let you know that our PWA changed URL. Its now at https://www.selio.com

Thanks.  :)

**Comment by mathiasbynens** [comment]
@julianmartinezmansell Care to submit a PR?

**Comment by julianmartinezmansell** [comment]
PR? its currently listed in the list of pwa.rocks, just that we changed the url. Thanks.

**Comment by mathiasbynens** [comment]
@julianmartinezmansell Exactly — could you submit a PR that updates the URL accordingly? Thanks!
