### ISSUE TITLE
Add Snapdeal

### ISSUE THREAD

**Issue by owencm** [operasoftware/pwa-list#57]
Snapdeal are a large ecommerce company with a PWA: https://m.snapdeal.com

**Comment by pepelsbey** [comment]
It gives 403 for `m.snapdeal.com` domain and hangs on `snapdeal.com`. Will test tomorrow in case it’s just a temrorary issue.

**Comment by andreasbovens** [comment]
Not seeing the install banner here...

**Comment by owencm** [comment]
Yeah I think there's some regression. We can forget this for now I think
