### ISSUE TITLE
Add Vaadin Expense Manager

### ISSUE THREAD

**Issue by vaadin-marcus** [operasoftware/pwa-list#63]
Would be great to have our Expense Manager Demo app featured on the site as an example of a Progressive Business Web Application

https://demo.vaadin.com/expense-manager

**Comment by pepelsbey** [comment]
It doesn’t trigger app install banner for some reason, investigating.

**Comment by vaadin-marcus** [comment]
Hm, interesting. I do get the banner on Chrome. Are there any documented differences in requirements between the two for installing the banner?

**Comment by pepelsbey** [comment]
Added in the [expense](https://github.com/operasoftware/pwa-list/tree/expense) branch, will test it a bit more and merge. Thank you for suggestion!

**Comment by vaadin-marcus** [comment]
Thanks!

**Comment by pepelsbey** [comment]
Added, will be deployed soon.
