### ISSUE TITLE
Add Google Spaces

### ISSUE THREAD

**Issue by benfrancis** [operasoftware/pwa-list#64]
https://spaces.google.com

**Comment by pepelsbey** [comment]
Thank you! It took a while to optimize [this logo](https://ssl.gstatic.com/social/spaces/ui/logo-lockup_0d2907370101e528ca18032c0c187d89.svg) I found on Spaces but it’s there in [spaces](https://github.com/operasoftware/pwa-list/tree/spaces) branch. Will test is a bit and merge it.

**Comment by pepelsbey** [comment]
Added
