### ISSUE TITLE
add vibration me

### ISSUE THREAD

**Issue by alpeer** [operasoftware/pwa-list#68]
https://www.vibration.me

 @pepelsbey

**Comment by pepelsbey** [comment]
“Works with Chrome Mobile” and Chrome logo is not correct since Vibration API is [supported in Chrome, Opera, Android Browser and Firefox](http://caniuse.com/#feat=vibration).

**Comment by andreasbovens** [comment]
Closing as the issue mentioned above still hasn't been fixed.
