### ISSUE TITLE
Add Meatscope

### ISSUE THREAD

**Issue by cdata** [operasoftware/pwa-list#69]
Hey team,

I was just introduced to https://pwa.rocks. I love the idea.

I would like to propose that my recent PWA experiment called Meatscope be included in the list. Meatscope is a PWA that lets users record and share gifs.

Here is the website: https://meatscope.camera/
Here is the Github repo: https://github.com/cdata/meat-scope

Chris

**Comment by pepelsbey** [comment]
Thank you for suggestion! Added, will be deployed soon.
