### ISSUE TITLE
Contribution guideline?

### ISSUE THREAD

**Issue by justinribeiro** [operasoftware/pwa-list#7]
What's the proper way to submit a PWA for inclusion? Would you simply prefer a pull request with the proper code + svg added to the list, or just tickets that can be addressed?

**Comment by pepelsbey** [comment]
Here’s a [good example](https://github.com/operasoftware/pwa-list/pull/10) of such PR, but here’s also [the list of conditions](https://github.com/operasoftware/pwa-list#conditions-for-inclusion-in-this-list) added to the readme.
