### ISSUE TITLE
Add 'Robots Chat' App

### ISSUE THREAD

**Issue by manolo** [operasoftware/pwa-list#74]
I would like my demo app added. It should be useful as reference for other users experimenting with polymer + pwa + pouchdb

Site is:
https://wc.demo.vaadin.com/robots/

**Comment by pepelsbey** [comment]
Is it OK that on iOS I see just a white page? PWAs don't work in Safari yet, but they supposed to be _progressive_ and just work in cases when it's not possible to add them to home screen.

**Comment by manolo** [comment]
@pepelsbey can you try again?, when I deployed I forgot to include the webcomponents polyfill

**Comment by pepelsbey** [comment]
@manolo, functionality is confusing, half of the buttons doesn’t work, site is loading way too slow, modal dialog is unusable on mobile. I wouldn’t call it a good example of PWA, sorry.
