### ISSUE TITLE
Calculate `HASH` for `service-worker.js` on build 

### ISSUE THREAD

**Issue by mathiasbynens** [operasoftware/pwa-list#79]
https://github.com/operasoftware/pwa-list/blob/c9b1226d18da897657e4285582e815ab1fb948d1/src/assets/service-worker.js#L4

**Comment by pepelsbey** [comment]
I haven’t figured out how to get a check sum for an uknown list of files yet. I don’t want to copy-paste paths every time new app added.

**Comment by pepelsbey** [comment]
I beleive some of the [Dev.Opera’s code](https://github.com/operasoftware/devopera/blob/master/gulp/tasks/cache.js) could be reused here.

**Comment by mathiasbynens** [comment]
We could put all the “unknown”/unpredictable files in a separate directory.

**Comment by pepelsbey** [comment]
@mathiasbynens, every new site added to the list is unknown. It’s already way to complicated to add a new app:

1. Add logo
2. Change CSS
3. Change HTML

And you’ll also have to add logo to SW. I have some ideas how to solve it but it will require some structural changes.

**Comment by mathiasbynens** [comment]
See #119. The next step is to populate [the list of images in the service worker](https://github.com/operasoftware/pwa-list/blob/6caeb5a0a9c9c18166990fde8dc12b233e4fdadb/src/assets/service-worker.js#L19-L66) dynamically. I’ll tackle that in a follow-up PR.

**Comment by mathiasbynens** [comment]
#120
