### ISSUE TITLE
Add Wave-PD1

### ISSUE THREAD

**Issue by alexgibson** [operasoftware/pwa-list#8]
https://alexgibson.github.io/wavepad/

Repo: https://github.com/alexgibson/wavepad

**Comment by andreasbovens** [comment]
Nice one! I've filed a pull request with a fix for a path issue: https://github.com/alexgibson/wavepad/pull/3

**Comment by alexgibson** [comment]
Thanks for the PR! Merged so the issue should be corrected now :)

**Comment by alexgibson** [comment]
Will deploy this change shortly

**Comment by alexgibson** [comment]
So, I went ahead and ended up changing the scope of the manifest, so it no longer points to the root. Hopefully this should still fix the issue in the same way. Please let me know if not!

**Comment by pepelsbey** [comment]
@alexgibson, could you please file a PR? Here’s a good example #10:

- Add link to `index.html`, `list.scss` and `README.md`
- Provide SVG icon

If not, could you please at least give us your logo in any vector format?

**Comment by alexgibson** [comment]
Sure thing - only thing I don't have is a vector asset for the icon unfortunately, although I do have a large rasterised version. Will this suffice?

**Comment by pepelsbey** [comment]
@alexgibson, now you have it:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 224 224"><defs><linearGradient id="a" x1="112" y1="220" x2="112" y2="4" gradientUnits="userSpaceOnUse"><stop offset=".03" stop-color="#ccc" stop-opacity=".61"/><stop offset=".04" stop-color="#cbcbcb" stop-opacity=".58"/><stop offset=".1" stop-color="#c4c4c4" stop-opacity=".42"/><stop offset=".16" stop-color="#bfbfbf" stop-opacity=".29"/><stop offset=".24" stop-color="#bbb" stop-opacity=".18"/><stop offset=".32" stop-color="#b7b7b7" stop-opacity=".1"/><stop offset=".43" stop-color="#b5b5b5" stop-opacity=".04"/><stop offset=".58" stop-color="#b3b3b3" stop-opacity=".01"/><stop offset="1" stop-color="#b3b3b3" stop-opacity="0"/></linearGradient></defs><title>wavepad</title><rect x="8" y="8" width="208" height="208" rx="29.98" ry="29.98"/><path d="M112 40a72 72 0 1 1-72 72 72 72 0 0 1 72-72m0-17a89 89 0 1 0 89 89 89.13 89.13 0 0 0-89-89z" fill="#1f2325"/><path d="M112 74a38 38 0 1 1-38 38 38 38 0 0 1 38-38m0-17.05A55.05 55.05 0 1 0 167.05 112 55.12 55.12 0 0 0 112 56.95z" fill="#1f2325"/><circle cx="112" cy="112" r="21" fill="#1f2325"/><rect x="4" y="4" width="216" height="216" rx="33.98" ry="33.98" fill="url(#a)"/><path d="M186 8a30 30 0 0 1 30 30v148a30 30 0 0 1-30 30H38a30 30 0 0 1-30-30V38A30 30 0 0 1 38 8h148m0-8H38A38 38 0 0 0 0 38v148a38 38 0 0 0 38 38h148a38 38 0 0 0 38-38V38a38 38 0 0 0-38-38z" fill="#da1a33"/></svg>
```
Close enough, I think.

![image](https://cloud.githubusercontent.com/assets/105274/13195522/93c61c3c-d7c5-11e5-808b-09a73833071c.png)

**Comment by alexgibson** [comment]
Perfect, thanks!
