### ISSUE TITLE
Would be really helpful if showcased PWA were also categorized by tech stack used. (suggestion)

### ISSUE THREAD

**Issue by jasan-s** [operasoftware/pwa-list#87]
I am personally very excited about PWA  but can't seem to figure out how integrate the PWA features in a react+redux app.

**Comment by pepelsbey** [comment]
Our main focus is to showcase PWA apps, it doesn't matter what technologies they use. See @addyosmani’s [Progressive Web Apps across all frameworks](http://youtu.be/srdKq0DckXQ) talk for more details regarding React, etc.
