### ISSUE TITLE
Please add progressive web flap

### ISSUE THREAD

**Issue by jsonthor** [operasoftware/pwa-list#89]
Hi,

Could you add https://www.progressivewebflap.com/

To your site? It's a flappy bird html5 game, also working as a progressive web app. 

Thanks

**Comment by andreasbovens** [comment]
Seems to work nicely.

**Comment by jsonthor** [comment]
Thanks Andreas.

**Comment by pepelsbey** [comment]
Added in 6053c97, thank you!
