### ISSUE TITLE
Please add Pariksha.Co

### ISSUE THREAD

**Issue by jxcku** [operasoftware/pwa-list#90]
https://lite.pariksha.co

**Comment by pepelsbey** [comment]
Thank you for your suggestion, but there’s problem. We’re not trying to collect every PWA on Internet, but the most valuable ones for promoting PWA. It’s hard to say what Pariksha is made for by visiting the main “light” page. Of course you could sign up for an account to see what it’s all about, but I doubt that anyone would do it. So I don’t think Pariksha suits this list’s purpose. Correct me if I’m wrong @andreasbovens.

BTW, `https://pariksha.co/` couldn’t be reached, only `http://pariksha.co/` redirects to `https://www.pariksha.co/`. I’d suggest configuring redirects to a canonical URL (whatever that is) in all possible cases: `www`, `http`, `https`.
