### ISSUE TITLE
Add Web App Manifest Generator

### ISSUE THREAD

**Issue by benfrancis** [operasoftware/pwa-list#97]
The web app manifest generator is a web app :)

https://tomitm.github.io/appmanifest/

**Comment by andreasbovens** [comment]
Whereas this is cool, I'm not sure pwa.rocks is the right place for it. It's not really something you'd use on your mobile phone.

**Comment by andreasbovens** [comment]
@mathiasbynens @pepelsbey what do you say?

**Comment by pepelsbey** [comment]
We could mention it in the readme, but I wouldn’t feature it on PWA.rocks
